### ISSUE TITLE
Configuration for "partial" resolution

### ISSUE THREAD

**Issue by ioggstream** [jfinkhaeuser/prance#23]
## Expected Behaviour
I wish a parameter for a partial resolution of items, eg:

  - append external references to `components`
  - retain inner references to `#/components/schemas/...`

### Minimal Example Spec
```
...
schemas:
  A:
    properties:
      a: string
      b:
         $ref: https://foo.com/#B         
...
```

should become

```
...
schemas:
  A:
    a: string
    b: 
        $ref: '#/components/schemas/B'
  B:
    <all b stuff>
...

```
## Actual Behaviour

 Full resolution is done

@jfinkhaeuser
